[package]
name = "filament-sys"
version = "0.1.0"
authors = ["Walter Pearce <jaynus@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"

[build-dependencies]
cmake = "0.1"
cc = { version = "1.0", features = ["parallel"] }